### ISSUE TITLE
Failed to read data (1.6)

### ISSUE THREAD

**Issue by minacode** [azymohliad/watchmate#16]
I am getting a "Failed to read data" error when connecting to a watch with InfiniTime 1.6. 
This means, that I cannot setup a watch I bought, because they are shipped with that version.

**Comment by azymohliad** [comment]
Thanks, that's a helpful report. I think it should be easy to fix. Will try to look at it hopefully tonight, maybe throughout next week.

**Comment by minacode** [comment]
I used another companion for the moment, so don't stress yourself. 
Want to add that this project is my favorite companion app right now 👍

**Comment by azymohliad** [comment]
It was indeed not hard to fix. No worries about me stressing, I had time today, and if it ships with 1.6 (I somehow didn't know that), then it's pretty crucial to support it.

With this fix it doesn't stop reading out data from the watch after it encounters the first error (step count in case of 1.6), so everything else works as expected. I tested down to 0.8.3, and was able to OTA upgrade it back to 1.11

![Screenshot from 2023-03-19 20-43-34](https://user-images.githubusercontent.com/4020369/226200611-d2598be6-bbe3-4d3b-92da-6d5ef557b1f0.png)

**Comment by azymohliad** [comment]
v0.4.4 with the fix is out. Ready to update from AUR, should be available on Flathub within a few hours,
