### ISSUE TITLE
Packaging and distribution

### ISSUE THREAD

**Issue by 13werwolf13** [azymohliad/watchmate#20]
hi
I really liked your project and packaged it for opensuse. you can see how it's done [here](https://build.opensuse.org/package/show/home:Werwolf2517/watchmate).
but in order to consider the case completed, you need to add a .desktop file and an icon. I can do the first one myself and offer you a PR, but the second one is not available to me. please tell me if this is in the plans?

P.S.: sorry for my english

**Comment by azymohliad** [comment]
Hi, and thank you for making an OpenSUSE package for it!

Icon and .desktop file are available in the [assets](https://github.com/azymohliad/watchmate/tree/main/assets) directory. [Here's](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=watchmate-git) how they're used from ArchLinux package manifest, for example.

(no worries about English, everything is perfectly clear)
