### ISSUE TITLE
bug: Failed to get github releases

### ISSUE THREAD

**Issue by sbe-arg** [azymohliad/watchmate#28]
Unsure whats going on but works downloading and installing via files manually.

![image](https://github.com/azymohliad/watchmate/assets/23391642/3889943c-6d0b-4eb6-96e4-047793fb5e2f)

**Comment by azymohliad** [comment]
Interesting. I assume it happens every time for you, not just once? And I guess you can download the release from github from the same device/network manually without issues? If so, could you please run it from the terminal and collect the logs?

**Comment by sbe-arg** [comment]
Sorry I have been out of action for a bit Ill try this in a few days

**Comment by sbe-arg** [comment]
I forgot to confirm this but its been self resolved. Its been working fine and have been flashing successfully.
