### ISSUE TITLE
Doesn't recover from system suspend

### ISSUE THREAD

**Issue by grahamvh** [azymohliad/watchmate#31]
Hello!
Watchmate doesn't recover after a suspend of my phone, and needs to be relaunched.

## Steps to reproduce:
1. Launch watchmate
2. Either wait for your computer/phone to suspend or manually trigger a suspend
3. Wake the computer/phone up
4. Watchmate shows a blank window where it once showed the pinetime information (and the music controls stop working on the watch, if you had a music player running)

## System Information
OS: PureOS 10 (Byzantium)
Installed From: Flatpak
Version: 0.4.5

## Net Effect
On phones where the suspend time tends to be 1-2 min, this means that if I pause for too long, I need to not only wake it back up, but log back in and relaunch watchmate. It's an annoyance, and somewhat defeats the utility of being able to play/pause from the pinetime.

**Comment by grahamvh** [comment]
Cool, thanks for taking a look.

**Comment by azymohliad** [comment]
Oops, I keep forgetting merging PRs automatically closes the mentioned issues. Anyway, this should be fixed now in v0.5.0, which should be up on Flathub in a few hours and hopefully soon in available distro packages. Please, don't hesitate to reopen if it still doesn't work for you

**Comment by grahamvh** [comment]
Gave it a try, it works much better! Thank you! 

I still see this occasionally on my Librem 5, but not on my laptop. Watchmate will just spin trying to reconnect, and won't succeed until I reset the watch(restarting watchmate has no effect). As I have not been able to reproduce this with my laptop, I suspect some odd interaction between the librem 5 and the PineTime. Thus likely not a watchmate issue.

I can also make this state happen consistently if I go out of range of the Librem 5. Again, this doesn't happen on the laptop.

I think you can close this issue though. Works much better after this fix :)

**Comment by grahamvh** [comment]
And now I can't reproduce it :P. I'll open a new bug if it happens again.
