### ISSUE TITLE
Proposal: Automatic reconnect

### ISSUE THREAD

**Issue by eacelmar96** [azymohliad/watchmate#34]
Hello,

thank you for the great work. Sadly, my InfiniTime keeps disconnecting after a few minutes without reconnecting, unless I open the app and reconnect it manually. 

Would it be possible to have WatchMate do a few reconnection attempts automatically, once it loses the connection to a PineTime known to WatchMate? This would be great! Sadly I don't know Rust neither do I understand your code very well, so I can not fork it and do it on my own. 

Best,
Al

PS: I guess the disconnections have something to do with InfiniTime or BlueZ, but not with WatchMate.

**Comment by azymohliad** [comment]
Hey, yeah, that's a reasonable feature to have, and I think people asked for it before in the PineTime matrix chat. Thanks for making an issue for it, it helps with motivation and priorities, and it will probably be among the first things to do once I get another doze of motivation to work on the app, but not sure when.

**Comment by azymohliad** [comment]
I've implemented a basic version of it today (#41), it seems to work well for me. Will test it more, implement a few more features, and hopefully release it soon

**Comment by azymohliad** [comment]
[v0.5.0](https://github.com/azymohliad/watchmate/releases/tag/v0.5.0) is out. It should be up on Flathub in a few hours and hopefully soon in community distro packages. I'll close the issue now. If it doesn't work for you, I'd appreciate a bug report :)
