### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [azymohliad/watchmate#9]
The current summary `Sync and integrate with PineTime smart watch` is a bit too long (should be less than 35 characters). Summaries don't need to describe the whole feature set in detail, I think it could be simplified to something like `Sync your PineTime watch`.

These are the appdata summary guidelines: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata#summary

**Comment by azymohliad** [comment]
I'm very open to change it. I never really liked the current one.

How important is it to use imperative tone? I'm really struggling to come up with a verb that summarizes it well. I don't like "sync" very much as it describes one particular feature among many rather than summarizing them all. I can't think of anything clearer than "PineTime smart watch companion app".

**Comment by bertob** [comment]
It doesn't have to be imperative, but it's usually a good idea. "PineTime smart watch companion app" is a bit too long and detailed, but "PineTime watch companion" could work. That said, the imperative option from above is still nicer IMO.

**Comment by GameTec-live** [comment]
Manage your PineTime (Even shorter XD)

**Comment by azymohliad** [comment]
I've been thinking about it in the background for a bit. I think "manage" describes exactly what "sync" is missing, but it's true the other way around too. If I think about app features, then I'd say "sync" summarizes reading data from the watch, setting time, and sending notifications; and "manage" summarizes OTA firmware upgrade and external resources management. There's also media player control (which was the reason I used "integrate"), but I'd rather cut this than any of the above.

How do you folks like "Sync and manage your PineTime" (30 characters)? Also, do you think it's ok to not explain that PineTime is a smart watch? "Sync and manage a PineTime watch" (33 characters) seems clearer to those who don't know what PineTime is, but it's less concise.

**Comment by bertob** [comment]
I wouldn't worry about explaining the PineTime, the icon is a watch and if people don't have the device the app isn't useful to them anyway. "Sync and manage your PineTime" could work, but IMO the sync isn't essential and could be dropped.

**Comment by azymohliad** [comment]
Alright, I'm probably overthinking it. Just merged #12 with "Manage your PineTime"

**Comment by azymohliad** [comment]
This is now released, so I'm closing the issue
